# Generated by Django 3.2.25 on 2024-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_blog_title_30d824_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='title_content_fulltext',
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['content'], name='content_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title', 'content'], name='fulltext_idx'),
        ),
    ]
